### ISSUE TITLE
Keypad is not work

### ISSUE THREAD

**Issue by kay54068** [FASTSHIFT/lv_gba_emu#2]
Hi @FASTSHIFT ,

This is a amusing project.   i try build and run but the screen keypad seem not work.  how do fixed it?

my test environment is 

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

gcc version:

```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by FASTSHIFT** [comment]
@kay54068 
This is caused by the higher priority of SDL keyboard input. You can simply remove the `gba_port_init()` call in `main.c` first, and you can use the screen to simulate the keyboard. I'll refine the command line parser later so the user can choose the type of input.

If you want to use the keyboard to operate, refer to the following key table. 

```c
    static const SDL_Keycode key_map[] = {
      SDL_SCANCODE_X, /* GBA_JOYPAD_B */
      0, /* GBA_JOYPAD_Y */
      SDL_SCANCODE_BACKSPACE, /* GBA_JOYPAD_SELECT */
      SDL_SCANCODE_TAB, /* GBA_JOYPAD_START */
      SDL_SCANCODE_UP, /* GBA_JOYPAD_UP */
      SDL_SCANCODE_DOWN, /* GBA_JOYPAD_DOWN */
      SDL_SCANCODE_LEFT, /* GBA_JOYPAD_LEFT */
      SDL_SCANCODE_RIGHT, /* GBA_JOYPAD_RIGHT */
      SDL_SCANCODE_Z, /* GBA_JOYPAD_A */
      0, /* GBA_JOYPAD_X */
      SDL_SCANCODE_L, /* GBA_JOYPAD_L */
      SDL_SCANCODE_R, /* GBA_JOYPAD_R */
      0, /* GBA_JOYPAD_L2 */
      0, /* GBA_JOYPAD_R2 */
      0, /* GBA_JOYPAD_L3 */
      0 /* GBA_JOYPAD_R3 */
    };
```

If you want to modify the key, you can find it in `gba_port_sdl2.c` and modify it.

**Comment by kay54068** [comment]
@FASTSHIFT 

Got it.  i remark the gba_port_init callback in main.c the keypad can work.
Do you have plans to coexist with SDL keyboard and Keypad?

**Comment by FASTSHIFT** [comment]
> @FASTSHIFT
> 
> Got it. i remark the gba_port_init callback in main.c the keypad can work. Do you have plans to coexist with SDL keyboard and Keypad?

Supported in this [commit](https://github.com/FASTSHIFT/lv_gba_emu/commit/f1c9c1a5b94d2fc44b99f5cdfeab4adf9eb5d340).

**Comment by kay54068** [comment]
@FASTSHIFT 

it's work for me. 
sdl2 and evdev can work together.

thanks.
