### ISSUE TITLE
how to destroy GBA use memory 

### ISSUE THREAD

**Issue by kay54068** [FASTSHIFT/lv_gba_emu#3]
HI @FASTSHIFT,

I want integrated into NXP guider  framework, I need to have a function that can delete the memory used by GBA.
Do you have any suggest ?

**Comment by FASTSHIFT** [comment]
@kay54068 
Supported in this [commit](https://github.com/FASTSHIFT/lv_gba_emu/commit/589610af60b1253b5a10e868187e056fc528f63a)
Call the `lv_gba_emu_del` function to free the memory of the entire gba emulator.

**Comment by kay54068** [comment]
Hi @FASTSHIFT 

Got it. thanks.
your new code arch very nice , worthy of further study.
